main: svar.ajneb97.ServerVariables
version: ${project.version}
name: GlobalServerVariables
api-version: 1.13
softdepend: [PlaceholderAPI]

commands:
  globalservervariables:
    description: Main command of GlobalServerVariables
    aliases: [gvar]